package com.feirs.backend.models;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * The centralized, multi-tenant master ledger.
 * Records every authentication attempt, biometric scan, and data modification
 * across the entire platform. Provides data for every single dashboard metric
 * and guarantees legal accountability.
 *
 * Per Audit Logs Table Plan.pdf:
 *   - PK is BIGINT auto-increment (not VARCHAR) — log tables grow into millions
 *     of rows and need native 64-bit integer indexing for millisecond sorting.
 *   - FK references (actor_id, target_id, institution_id) are stored as plain
 *     VARCHAR strings, NOT @ManyToOne mappings, because they can refer to
 *     a Super Admin, Institution Admin, Operator, or Citizen interchangeably.
 *   - institution_id column named per Database Tables Correction Plan.pdf
 *     (renamed from institution_admin_id).
 */
@Entity
@Table(name = "audit_logs")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AuditLog {

    /**
     * Auto-incrementing 64-bit integer PK.
     * BIGSERIAL in PostgreSQL — ensures the database can index and sort
     * millions of events in milliseconds.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "log_id", nullable = false, updatable = false)
    private Long logId;

    // ── The "Who" (Actor Details) ────────────────────────

    /**
     * System ID of the person who performed the action
     * (e.g., FEIRS-OP-90812, FEIRS-SA-ROOT, FEIRS-IA-MSRIT).
     * Plain VARCHAR — NOT a @ManyToOne because this can be any role type.
     */
    @Column(name = "actor_id", nullable = false, length = 50)
    private String actorId;

    /**
     * Role of the actor: SUPER_ADMIN, INSTITUTION_ADMIN, OPERATOR.
     * Used for GROUP BY queries to generate pie charts like "Platform Activity by Role."
     */
    @Column(name = "actor_role", nullable = false, length = 50)
    private String actorRole;

    // ── The "Where" (Multi-Tenant Isolation) ─────────────

    /**
     * Tags the event to a specific institution for multi-tenant filtering.
     *
     * When the Institution Admin views their staff's scan history, the backend
     * runs: SELECT * FROM audit_logs WHERE institution_id = 'FEIRS-INST-CITY'
     *
     * Nullable: actions performed by the Super Admin do not belong to a
     * specific hospital.
     *
     * Column name uses institution_id per Database Tables Correction Plan.pdf.
     */
    @Column(name = "institution_id", length = 50)
    private String institutionId;

    // ── The "What" (Action Details) ──────────────────────

    /**
     * Strict uppercase string defining the event category.
     * Values: EMERGENCY_SCAN, CITIZEN_ENROLL, PROFILE_DELETED,
     *         LOGIN_ATTEMPT, APPROVE_INSTITUTION, REJECT_INSTITUTION,
     *         CHANGE_REQUEST_SUBMITTED, CHANGE_REQUEST_RESOLVED, etc.
     */
    @Column(name = "action_type", nullable = false, length = 100)
    private String actionType;

    /**
     * System ID of the entity that was affected.
     * If an Operator scans a patient: actor_id = Operator, target_id = FEIRS-CIT-XXX.
     * If Super Admin approves a hospital: target_id = FEIRS-INST-XXX.
     * Nullable for events without a specific target (e.g., general login).
     */
    @Column(name = "target_id", length = 50)
    private String targetId;

    /**
     * Outcome: SUCCESS or FAILED.
     * Used for security alerts — e.g., SELECT * FROM audit_logs
     * WHERE action_status = 'FAILED' AND action_type = 'LOGIN_ATTEMPT'.
     */
    @Column(name = "action_status", nullable = false, length = 20)
    private String actionStatus;

    // ── The "Context" (Human & Machine Readability) ──────

    /**
     * Plain-English summary generated by Spring Boot for UI display.
     * e.g., "Operator FEIRS-OP-90812 successfully performed an Emergency
     * Scan on Citizen FEIRS-CIT-40921."
     */
    @Column(name = "event_description", nullable = false, columnDefinition = "TEXT")
    private String eventDescription;

    /**
     * Enterprise cybersecurity standard. If a malicious action occurs,
     * logging the IP address allows the Super Admin to block that
     * specific network from accessing the platform.
     */
    @Column(name = "ip_address", length = 50)
    private String ipAddress;

    // ── The "When" (Timestamp) ───────────────────────────

    /**
     * Records the exact millisecond the action occurred.
     * Crucial for chronological sorting and metrics like "Total Scans Today."
     */
    @Column(name = "timestamp", nullable = false)
    private LocalDateTime timestamp;

    // ── JPA Lifecycle Callback ────────────────────────────

    @PrePersist
    protected void onCreate() {
        if (this.timestamp == null) {
            this.timestamp = LocalDateTime.now();
        }
    }
}
