package com.feirs.backend.models;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Root-level architectural master table.
 * Strictly isolated from standard operations to maintain absolute platform security.
 *
 * Per Super Admin Table Plan.pdf — 10 definitive columns.
 * PK: super_admin_id (e.g., FEIRS-SA-ROOT) — immutable VARCHAR, manually assigned.
 */
@Entity
@Table(name = "super_admins")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SuperAdmin {

    /**
     * Permanent System ID (e.g., FEIRS-SA-ROOT).
     * Manually assigned VARCHAR primary key — no auto-generation.
     * Guarantees root identity can never be duplicated and supports Dual Login architecture.
     */
    @Id
    @Column(name = "super_admin_id", length = 50, nullable = false, unique = true, updatable = false)
    private String superAdminId;

    /**
     * The ultimate recovery anchor for the platform.
     * UNIQUE + NOT NULL enforced at the database level.
     */
    @Column(name = "master_email", nullable = false, unique = true, length = 255)
    private String masterEmail;

    /**
     * Bcrypt-encrypted password string generated by Spring Security.
     * Plain-text passwords are never stored.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * Display name (e.g., "System Architect").
     * Nullable so CommandLineRunner can inject the account on first startup
     * using only email + password, prompting profile completion later.
     */
    @Column(name = "admin_name", length = 150)
    private String adminName;

    /**
     * International dialing code (e.g., "+91").
     * Separated from main number for clean data formatting required by SMS/WhatsApp APIs.
     */
    @Column(name = "phone_country_code", length = 10)
    private String phoneCountryCode;

    /**
     * Direct 10-digit contact number for high-level system operations.
     */
    @Column(name = "phone_number", length = 20)
    private String phoneNumber;

    /**
     * Cloud-hosted avatar URL.
     * Stored as TEXT link instead of binary to keep database queries lightning fast.
     */
    @Column(name = "profile_photo_url", columnDefinition = "TEXT")
    private String profilePhotoUrl;

    /**
     * Vital operational metric for enterprise dashboard — "Last Login: [Date & Time]".
     */
    @Column(name = "last_login_at")
    private LocalDateTime lastLoginAt;

    /**
     * Permanent record of the exact millisecond the root account was created.
     * Not updatable after insert.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Tracks the exact time of the most recent profile modification.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
